//Student Name: Scott Cardiff//
//Purpose of Screen: This si the scripting for the HTML and for validation of correct information//
//Student ID: C00311728//
//Name of Screen: Add Eye Test//
//Date: 24/03/2026//

    
    //
    const form = document.getElementById("eyeTestForm"); //form is now stored into the id form the html 'eyeTestForm' and performs code and requirements
    const leftLens = document.getElementById("left_lens");
    const rightLens = document.getElementById("right_lens");
    const dateOfTest = document.getElementById("date_of_test");

    form.addEventListener("submit", function (e) {      //When the form is submitted, the actual event 'submit', all this requirements is performed when the submit is clicked
        

       
        const lensPattern = /^[+-]?\d{1,2}(\.\d{1,2})?$/; // [+-]= allows either + or -, ? is optional, 
        // \d{1,2} = allows up to 2 digits, (\.\d{1,2})? = is the deciaml portion. This pattern was generated by AI to understand
        //how the correct pattern can be done.

        // This is validating the Left Lens to ensure the patter is correct when putting into db
        if (!lensPattern.test(leftLens.value)) {    //.value is used to check the actual value inputted in the field is correct, ! is used IF the value is false
            alert("Left lens must be a valid number (example: -1.25)");
            e.preventDefault() // Stops the form from being submitted
        }

        // And now validating the Right Lens
        if (!lensPattern.test(rightLens.value )) {
           alert("Right lens must be a valid number (example: -1.25)");
           e.preventDefault()
        }

        const selectedDate = new Date(dateOfTest.value);    //new Date created for inputting the date of the test
        const today = new Date();
        today.setHours(0,0,0,0);

        if (selectedDate < today) {
            alert("Date of test must not be in the past.");
            e.preventDefault();
        }

        const clicked = document.activeElement?.name;
        if (clicked === "search_customer") return;
    });

;
